import { Orders } from "../../../store/slices/managerSlice.ts";
import OrderCheck from "./OrderCheck.tsx";
import { useAppSelector } from "../../../store/hooks/hooks.ts";

const CookPage = () => {
  // const orders: Orders[] = [
  //   {
  //     id: 1,
  //     client_id: "1234249296",
  //     company_id: 1,
  //     is_delivery: true,
  //     delivery_id: "DEL123456",
  //     delivery_name: "Dostavista",
  //     products: [
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 1,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 2,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 3,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //     ],
  //     status: "active",
  //     rejected_text: "",
  //     bonus_used: false,
  //     bonus_amount: 0,
  //     delivery_price: 100,
  //     done_time: "2024-07-19T15:30:00Z",
  //     user_name: "Nurzhan",
  //     address: {
  //       long: 76.876214,
  //       lat: 43.218921,
  //       parsed: "улица Жандосова, 49",
  //     },
  //     exact_address: "94 квартира",
  //     phone: "77074862447",
  //     kaspi_phone: "77074862447",
  //     client_comment: "Позвоните за 10 минут до прибытия",
  //     created_at: "2024-07-19T12:00:00Z",
  //     updated_at: "2024-07-19T12:00:00Z",
  //     actions: [],
  //     order_time: "2024-07-19T11:50:00Z",
  //   },
  //   {
  //     id: 2,
  //     client_id: "9876543210",
  //     company_id: 2,
  //     is_delivery: false,
  //     delivery_id: null,
  //     delivery_name: "",
  //     products: [
  //       {
  //         amount: 1,
  //         client_comment: "",
  //         price: 2500,
  //         product_id: 4,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 1,
  //         client_comment: "",
  //         price: 2500,
  //         product_id: 15,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //     ],
  //     status: "active",
  //     rejected_text: "",
  //     bonus_used: true,
  //     bonus_amount: 500,
  //     delivery_price: 0,
  //     done_time: "2024-07-18T20:45:00Z",
  //     user_name: "Aidos",
  //     address: {
  //       long: 76.875214,
  //       lat: 43.217921,
  //       parsed: "проспект Абая, 100",
  //     },
  //     exact_address: "10 этаж, офис 105",
  //     phone: "77071234567",
  //     kaspi_phone: "77071234567",
  //     client_comment: "Привезите к главному входу",
  //     created_at: "2024-07-18T19:00:00Z",
  //     updated_at: "2024-07-18T19:00:00Z",
  //     actions: [],
  //     order_time: "2024-07-18T18:50:00Z",
  //   },
  //   {
  //     id: 4,
  //     client_id: "9876543210",
  //     company_id: 2,
  //     is_delivery: false,
  //     delivery_id: null,
  //     delivery_name: "",
  //     products: [
  //       {
  //         amount: 1,
  //         client_comment: "",
  //         price: 2500,
  //         product_id: 4,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 1,
  //         client_comment: "",
  //         price: 2500,
  //         product_id: 15,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //     ],
  //     status: "active",
  //     rejected_text: "",
  //     bonus_used: true,
  //     bonus_amount: 500,
  //     delivery_price: 0,
  //     done_time: "2024-07-18T20:45:00Z",
  //     user_name: "Aidos",
  //     address: {
  //       long: 76.875214,
  //       lat: 43.217921,
  //       parsed: "проспект Абая, 100",
  //     },
  //     exact_address: "10 этаж, офис 105",
  //     phone: "77071234567",
  //     kaspi_phone: "77071234567",
  //     client_comment: "Привезите к главному входу",
  //     created_at: "2024-07-18T19:00:00Z",
  //     updated_at: "2024-07-18T19:00:00Z",
  //     actions: [],
  //     order_time: "2024-07-18T18:50:00Z",
  //   },
  //   {
  //     id: 6,
  //     client_id: "9876543210",
  //     company_id: 2,
  //     is_delivery: false,
  //     delivery_id: null,
  //     delivery_name: "",
  //     products: [
  //       {
  //         amount: 1,
  //         client_comment: "",
  //         price: 2500,
  //         product_id: 4,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 1,
  //         client_comment: "",
  //         price: 2500,
  //         product_id: 15,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //     ],
  //     status: "active",
  //     rejected_text: "",
  //     bonus_used: true,
  //     bonus_amount: 500,
  //     delivery_price: 0,
  //     done_time: "2024-07-18T20:45:00Z",
  //     user_name: "Aidos",
  //     address: {
  //       long: 76.875214,
  //       lat: 43.217921,
  //       parsed: "проспект Абая, 100",
  //     },
  //     exact_address: "10 этаж, офис 105",
  //     phone: "77071234567",
  //     kaspi_phone: "77071234567",
  //     client_comment: "Привезите к главному входу",
  //     created_at: "2024-07-18T19:00:00Z",
  //     updated_at: "2024-07-18T19:00:00Z",
  //     actions: [],
  //     order_time: "2024-07-18T18:50:00Z",
  //   },
  //   {
  //     id: 5,
  //     client_id: "1234249296",
  //     company_id: 1,
  //     is_delivery: true,
  //     delivery_id: "DEL123456",
  //     delivery_name: "Dostavista",
  //     products: [
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 1,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 2,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 3,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //     ],
  //     status: "active",
  //     rejected_text: "",
  //     bonus_used: false,
  //     bonus_amount: 0,
  //     delivery_price: 100,
  //     done_time: "2024-07-19T15:30:00Z",
  //     user_name: "Nurzhan",
  //     address: {
  //       long: 76.876214,
  //       lat: 43.218921,
  //       parsed: "улица Жандосова, 49",
  //     },
  //     exact_address: "94 квартира",
  //     phone: "77074862447",
  //     kaspi_phone: "77074862447",
  //     client_comment: "Позвоните за 10 минут до прибытия",
  //     created_at: "2024-07-19T12:00:00Z",
  //     updated_at: "2024-07-19T12:00:00Z",
  //     actions: [],
  //     order_time: "2024-07-19T11:50:00Z",
  //   },
  //   {
  //     id: 3,
  //     client_id: "1234249296",
  //     company_id: 1,
  //     is_delivery: true,
  //     delivery_id: "DEL123456",
  //     delivery_name: "Dostavista",
  //     products: [
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 1,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 2,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //       {
  //         amount: 2,
  //         client_comment: "",
  //         price: 5000,
  //         product_id: 3,
  //         active_modifier: null,
  //         additions: [],
  //       },
  //     ],
  //     status: "active",
  //     rejected_text: "",
  //     bonus_used: false,
  //     bonus_amount: 0,
  //     delivery_price: 100,
  //     done_time: "2024-07-19T15:30:00Z",
  //     user_name: "Nurzhan",
  //     address: {
  //       long: 76.876214,
  //       lat: 43.218921,
  //       parsed: "улица Жандосова, 49",
  //     },
  //     exact_address: "94 квартира",
  //     phone: "77074862447",
  //     kaspi_phone: "77074862447",
  //     client_comment: "Позвоните за 10 минут до прибытия",
  //     created_at: "2024-07-19T12:00:00Z",
  //     updated_at: "2024-07-19T12:00:00Z",
  //     actions: [],
  //     order_time: "2024-07-19T11:50:00Z",
  //   },
  // ];

  const orders: Orders[] = useAppSelector(
    (state) => state.manager.orders,
  ).filter((order) => order.status === "active");

  return (
    <div
      className={
        "flex h-[100vh] max-h-[100vh] flex-col flex-wrap gap-8 overflow-y-hidden p-4"
      }
    >
      {orders.map((order) => {
        return <OrderCheck key={order.id} order={order} />;
      })}
    </div>
  );
};

export default CookPage;
